# Generated by Django 4.2.7 on 2025-12-24 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversiontask',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='conversiontask',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
